# -*- coding: utf-8 -*-
"""13 Semana - Tecnologías Base: IA + Recuperación Semántica + Web

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwCC7pkT-PCIIE1w169OHUn6jgW0QU4A
"""

!pip uninstall -y langchain langchain-core langchain-community langchain-google-genai

!pip install langchain==0.2.16
!pip install langchain-core==0.2.38
!pip install langchain-community==0.2.16
!pip install langchain-google-genai==1.0.10

!pip install langchain-text-splitters
!pip install chromadb
!pip install pypdf
!pip install python-docx
!pip install sentence-transformers
!pip install faiss-cpu

import os

from google.colab import files

from langchain_community.document_loaders import PyPDFLoader

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_community.vectorstores import Chroma

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain.chains import RetrievalQA

"""EDITAR EL API DE GOOGLE"""

os.environ["GOOGLE_API_KEY"] = "TU_API_KEY_AQUI"

uploaded = files.upload()

loader = PyPDFLoader("don-quijote-de-la-mancha-miguel-de-cervantes (2).pdf")

documents = loader.load()

print(documents[0].page_content)

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

texts = text_splitter.split_documents(documents)

print(len(texts))

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db = Chroma.from_documents(
    documents=texts,
    embedding=embeddings
)

retriever = db.as_retriever(
    search_kwargs={"k": 3}
)

import google.generativeai as genai
import os

genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

for m in genai.list_models():
    print(m.name)

llm = ChatGoogleGenerativeAI(
    model="models/gemini-2.5-flash",
    temperature=0.3
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever
)

respuesta = qa_chain.run(
    "¿De qué trata el documento?"
)

print(respuesta)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    return_source_documents=True
)

from langchain.prompts import PromptTemplate

prompt = PromptTemplate.from_template("""
Usa el contexto del documento para responder.
Si la respuesta no está en el documento, usa tu conocimiento general.

Contexto:
{context}

Pregunta:
{question}

Respuesta clara:
""")

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type_kwargs={"prompt": prompt}
)

chain_type="stuff"

while True:
    pregunta = input("Tú: ")

    if pregunta.lower() == "salir":
        break

    respuesta = qa_chain.run(pregunta)

    print("Bot:", respuesta)

pip install flask flask-cors

import os

os.makedirs("rag", exist_ok=True)

code = """
def qa_chain(question):
    return "Respuesta simulada: " + question
"""

with open("rag/chain.py", "w") as f:
    f.write(code)

open("rag/__init__.py", "w").close()

with open("requirements.txt", "w") as f:
    f.write("""
flask
flask-cors
langchain
""")

with open("README.md", "w") as f:
    f.write("""
# Chatbot RAG con Flask

Proyecto de chatbot inteligente usando LangChain + Flask + embeddings.

## Cómo ejecutar
python app.py

## API
POST /chat
{"message": "hola"}
""")

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

from rag.chain import qa_chain  # tu RAG

@app.route("/chat", methods=["POST"])
def chat():
    data = request.json
    pregunta = data.get("message")

    respuesta = qa_chain.run(pregunta)

    return jsonify({"response": respuesta})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)

!git init

!git remote remove origin

!git push https://Jhon-fer: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@github.com/Jhon-fer/13-Semana---Tecnolog-as-Base-IA-Recuperaci-n-Sem-ntica-Web.git main

!git remote add origin https://Jhon-fer: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@github.com/Jhon-fer/13-Semana---Tecnolog-as-Base-IA-Recuperaci-n-Sem-ntica-Web.git

!git add .
!git commit -m "Descripción de mis nuevos cambios"
!git push origin main

# Este comando agrega el archivo del cuaderno y cualquier otro cambio pendiente
!git add "*.py"
!git add .

!git commit -m "Agregando el cuaderno de Colab con la lógica del Chatbot"

!git push origin main